[ req ]
default_bits        = 2048
default_md          = sha256
distinguished_name  = subject
req_extensions      = req_ext
x509_extensions     = req_ext
string_mask         = utf8only
prompt              = no

[ req_ext ]
basicConstraints        = CA:FALSE
nsCertType              = client
keyUsage                = nonRepudiation, digitalSignature, keyEncipherment, dataEncipherment
extendedKeyUsage        = clientAuth
nsComment               = "OpenSSL Tutorial for IRC5 OPC-UA"
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid,issuer
subjectAltName          = URI:urn:freeopcua:client

[ subject ]
countryName             = US
stateOrProvinceName     = FL         
localityName            = Gainesville 
organizationName        = UF
commonName              = PythonOpcUaClient